image: 
  name: node:18.4.0

definitions:
  steps:
    - step: &install
        name: Install dependencies
        caches:
          - node
        script:
          - npm install

    - step: &lint
        name: Lint
        script:
          - npm install --save-dev eslint
          - npm run lint

    - step: &test
        name: Tests
        script:
          - npm install --save-dev jest
          - npm run test

pipelines:
  pull-requests:
    '**':
      - step: *install
      - step: *lint
      - step: *test